### ISSUE TITLE
Invalid subscript 'vertexSH'

### ISSUE THREAD

**Issue by staakman** [unity3d-jp/UnityChanToonShaderVer2_Project#62] opened 2020-11-13 17:50 UTC
I'm getting the following issue on line 41 in UniversalToonBodyDoubleShadeWithFeather.hlsl

invalid subscript 'vertexSH'

```
Compiling Vertex program with LIGHTMAP_ON DIRLIGHTMAP_COMBINED _MAIN_LIGHT_SHADOWS _MAIN_LIGHT_SHADOWS_CASCADE _ENVIRONMENTREFLECTIONS_OFF _IS_PASS_FWDBASE _IS_TRANSCLIPPING_OFF _IS_ANGELRING_OFF _IS_CLIPPING_OFF _EMISSIVE_SIMPLE
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR
Disabled keywords: _NORMALMAP _ALPHATEST_ON _ALPHAPREMULTIPLY_ON _EMISSION _METALLICSPECGLOSSMAP _SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A _OCCLUSIONMAP _SPECULARHIGHLIGHTS_OFF _SPECULAR_SETUP _RECEIVE_SHADOWS_OFF _ADDITIONAL_LIGHTS_VERTEX _ADDITIONAL_LIGHTS _ADDITIONAL_LIGHT_SHADOWS _SHADOWS_SOFT _MIXED_LIGHTING_SUBTRACTIVE _SHADINGGRADEMAP _IS_TRANSCLIPPING_ON _IS_ANGELRING_ON UTS_USE_RAYTRACING_SHADOW _IS_CLIPPING_MODE _IS_CLIPPING_TRANSMODE _EMISSIVE_ANIMATION FOG_LINEAR FOG_EXP FOG_EXP2 UNITY_NO_DXT5nm UNITY_ENABLE_NATIVE_SHADOW_LOOKUPS UNITY_METAL_SHADOWS_USE_POINT_FILTERING UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF2 UNITY_PBS_USE_BRDF3 UNITY_NO_FULL_STANDARD_SHADER UNITY_HARDWARE_TIER1 UNITY_HARDWARE_TIER2 UNITY_HARDWARE_TIER3 UNITY_COLORSPACE_GAMMA UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS UNITY_LIGHTMAP_DLDR_ENCODING UNITY_LIGHTMAP_RGBM_ENCODING UNITY_VIRTUAL_TEXTURING
```

![image](https://user-images.githubusercontent.com/4894596/99104091-ce5c7580-25e0-11eb-9966-99d83f007611.png)

**Comment by H3idi-X** [comment] 2021-02-18 04:06
Thanks for reporting, but we were not able to reproduce the issue yet. Could you let us know which Unity and Universal RP version?

**Comment by H3idi-X** [comment] 2021-02-22 12:43
Hi, .

We released 2.2.2 today.
Will you please try this?

https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/releases/tag/urp-2.2.2

**Comment by staakman** [comment] 2021-02-22 14:39
Hi,

thanks for the reply. I will try this today :)

Op ma 22 feb. 2021 om 13:44 schreef higeometry <notifications@github.com>:

**Comment by H3idi-X** [comment] 2021-02-24 04:36
I found this still occurs when light map is enabled. I'm working on this.

**Comment by H3idi-X** [comment] 2021-03-08 01:39
Hi, we found that fixing this issue is hard without making drastic restructuring. If we fixed this vertxSH error, the next problem is texture number limitation and we will sometime come to see an error, maximum ps_4_0 sampler register index (16) exceeded. 

We had been spending long time to deal with this problem and we have decided to make new shader drastically improved, which,　we believe, can get over this issue. Will you please refrain from using light map, checking static in the inspector to UTS objects, for a certain period?

We started the new project a few weeks ago. Currently, we are mainly working on the legacy shader integration similar to Universal and HDRP. Next, we focus on HDRP improvement. Reducing the number of textures will be the next.

Thank you.
UTS team.

**Comment by staakman** [comment] 2021-03-10 08:59
thank you for all the work you've been doing. I'll test out the new project as soon as it comes out! :)

**Comment by H3idi-X** [comment] 2021-05-20 02:09
Hi, how was the result?

**Comment by H3idi-X** [comment] 2021-07-12 23:15
Hi, I close this. Please, submit another issue report if it happens again.
Thanks.

**Closed as completed by H3idi-X** 2021-07-12 23:15 UTC
