### ISSUE TITLE
UTS There's no shadow.

### ISSUE THREAD

**Issue by umbad** [unity3d-jp/UnityChanToonShaderVer2_Project#95] opened 2021-11-15 10:26 UTC
![1115](https://user-images.githubusercontent.com/50651748/141765680-62db37f4-0e34-4e02-8086-327c299e38b6.PNG)

No matter how hard you try, there's no shadow.

**Comment by H3idi-X** [comment] 2021-11-15 15:45
Hello, Thanks for reporting.
Would you please give us more specific information? **No shadow** means **not receiving shadow**, right?
If you are talking about Universal RP version and using newer than 2021.1, that will be fixed in the next release.

**Comment by TTXin** [comment] 2022-01-19 06:45
Hello higeometry-san,
I probably faced the same issue. The cube on the left is UTS and the the right is the standard material.
When do you plan to release the next version?

・Unity 2021.2.4f1
・URP Version 12.1.1
<img width="1234" alt="urputs" src="https://user-images.githubusercontent.com/9078388/150078198-cb319908-9c66-4121-8f3c-35d781333b2f.png">

**Comment by H3idi-X** [comment] 2022-01-19 10:33
Oh..., This is not shaded at all.
I'll try reproducing the issue.

**Comment by H3idi-X** [comment] 2022-01-20 12:13
Hi, We've just released [2.4.0](https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/releases/tag/urp-2.4.0). As far as we tested it is compatible with 2019.4, 2020.3, 2021.2 and 2022.1b3. Will you please try this release?

**Comment by H3idi-X** [comment] 2022-01-20 21:55
Oh, I forgot to mention. The new UTS has passed our in-house automated tests on various versions of Unity, plus we have visually checked the following versions.
| As far as we tested it is compatible with 2019.4, 2020.3, 2021.2 and 2022.1b3. Will you please try this release?

**Comment by TTXin** [comment] 2022-01-21 12:52
Thank you for your support.
I have confirmed that UTS/Universal 2.4.0 solved the issue.
Great job!
<img width="1233" alt="utsurpfixed" src="https://user-images.githubusercontent.com/9078388/150529961-9583ba64-bb95-4fde-ad18-7a608dab7ad7.png">

**Comment by NecroShade1829** [comment] 2022-01-25 18:49
Hello friends!

I'm trying to use the shader for a uni project. I'm trying to compose an indoor scene with 2 point lights that cast shadows on Unity 2021.2.0 and the shader version is 2.4.0 and I cannot get shadows being received by a mesh with an UTS material.
With a single directional light it worked fine, changing to a point light the shadows no longer appeared.

**Comment by H3idi-X** [comment] 2022-01-25 21:58
Hi, UTS materials don't receive punctual light shadows by design for all the render pipelines. We have no plans to change this.
https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/issues/86

**Comment by H3idi-X** [comment] 2022-01-26 19:15
Fixed in 2.4.0.

**Closed as completed by H3idi-X** 2022-01-26 19:15 UTC
